### ISSUE TITLE
Error releasifying package: Error executing file (255):

### ISSUE THREAD

**Issue by obonyojimmy** [unindented/electron-installer-windows#123]
**What version of `electron-installer-windows` are you using?**
Am using `electron-installer-windows` v 0.2.0

**What version of `node` and `npm` are you using?**
Nmp  v 3.10.
Node v 6.8.1
Mono v 3.2
Wine v 1.9.15

**What operating system are you using?**
Am building in linux with electron-packager , which build succesfully and i can run the .exe in windows platform with no problem 
However when i try to build the instller with 
` electron-installer-windows --src builds/radiotech-win32-x64/ --dest dist/installers/`

i get error 
Creating package (this may take a while)
Error: Error releasifying package: Error executing file (255): 
mono /usr/local/lib/node_modules/electron-installer-windows/vendor/squirrel/Squirrel-Mono.exe --releasify /tmp/electron-1161025-4708-q9sxh2.aeasq3erk9/radiotech_0.0.0/nuget/radiotech.0.0.0.nupkg --releaseDir /tmp/electron-1161025-4708-q9sxh2.aeasq3erk9/radiotech_0.0.0/squirrel --setupIcon /usr/local/lib/node_modules/electron-installer-windows/resources/icon.ico --loadingGif /usr/local/lib/node_modules/electron-installer-windows/resources/animation.gif
System.InvalidOperationException: The input package file /tmp/electron-1161025-4708-q9sxh2.aeasq3erk9/radiotech_0.0.0/squirrel/radiotech.0.0.0.nupkg targets no platform and cannot be transformed into a release package.
  at Squirrel.ReleasePackage.CreateReleasePackage (System.String outputFile, System.String packagesRootDir, System.Func`2 releaseNotesProcessor, System.Action`1 contentsPostProcessHook) [0x00000] in <filename unknown>:0 
  at Squirrel.Update.Program.Releasify (System.String package, System.String targetDir, System.String packagesDir, System.String bootstrapperExe, System.String backgroundGif, System.String signingOpts, System.String baseUrl, System.String setupIcon, Boolean generateMsi) [0x00000] in <filename unknown>:0 
  at Squirrel.Update.Program.executeCommandLine (System.String[] args) [0x00000] in <filename unknown>:0 
  at Squirrel.Update.Program.main (System.String[] args) [0x00000] in <filename unknown>:0 

    at /usr/local/lib/node_modules/electron-installer-windows/src/installer.js:360:21
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/electron-installer-windows/src/installer.js:62:5)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) 'Error: Error releasifying package: Error executing file (255): \nmono /usr/local/lib/node_modules/electron-installer-windows/vendor/squirrel/Squirrel-Mono.exe --releasify /tmp/electron-1161025-4708-q9sxh2.aeasq3erk9/radiotech_0.0.0/nuget/radiotech.0.0.0.nupkg --releaseDir /tmp/electron-1161025-4708-q9sxh2.aeasq3erk9/radiotech_0.0.0/squirrel --setupIcon /usr/local/lib/node_modules/electron-installer-windows/resources/icon.ico --loadingGif /usr/local/lib/node_modules/electron-installer-windows/resources/animation.gif\nSystem.InvalidOperationException: The input package file /tmp/electron-1161025-4708-q9sxh2.aeasq3erk9/radiotech_0.0.0/squirrel/radiotech.0.0.0.nupkg targets no platform and cannot be transformed into a release package.\n  at Squirrel.ReleasePackage.CreateReleasePackage (System.String outputFile, System.String packagesRootDir, System.Func`2 releaseNotesProcessor, System.Action`1 contentsPostProcessHook) [0x00000] in <filename unknown>:0 \n  at Squirrel.Update.Program.Releasify (System.String package, System.String targetDir, System.String packagesDir, System.String bootstrapperExe, System.String backgroundGif, System.String signingOpts, System.String baseUrl, System.String setupIcon, Boolean generateMsi) [0x00000] in <filename unknown>:0 \n  at Squirrel.Update.Program.executeCommandLine (System.String[] args) [0x00000] in <filename unknown>:0 \n  at Squirrel.Update.Program.main (System.String[] args) [0x00000] in <filename unknown>:0 \n\n    at /usr/local/lib/node_modules/electron-installer-windows/src/installer.js:360:21\n    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/electron-installer-windows/src/installer.js:62:5)\n    at emitTwo (events.js:111:20)\n    at ChildProcess.emit (events.js:191:7)\n    at maybeClose (internal/child_process.js:877:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)'

**Comment by unindented** [comment]
It looks like certain versions of `mono` cause problems with [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows). It has already been reported upstream: https://github.com/Squirrel/Squirrel.Windows/issues/580

**Comment by unindented** [comment]
Do you have `wine` installed by the way?

**Comment by unindented** [comment]
Other people complaining about the same error in other libraries: https://github.com/electron/windows-installer/issues/63

**Comment by obonyojimmy** [comment]
So i guess solution would be to upgrade `mono` ?

**Comment by unindented** [comment]
You can try that, but the safest way is probably to create the Windows installer in a Windows VM, or use a service like Appveyor.

**Comment by obonyojimmy** [comment]
Thanks a lot
