### ISSUE TITLE
Unable to create installer for Windows 10 (error releasifying package)

### ISSUE THREAD

**Issue by belltown** [unindented/electron-installer-windows#149]
**What version of `electron-installer-windows` are you using?**
electron-installer-windows@0.2.0

**What version of `node` and `npm` are you using?**
node: v6.9.5
npm: 3.10.10

**What operating system are you using?**
Windows 10 Pro 

**Can you compile the [example app](https://github.com/unindented/electron-installer-windows/tree/master/example) successfully?**
No

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/unindented/electron-installer-windows.git
$ cd electron-installer-windows/example
$ DEBUG='electron-installer-windows' npm run build
```

```
c:\ElectronProjects>node -v
v6.9.5

c:\ElectronProjects>npm --version
3.10.10

c:\ElectronProjects>git clone https://github.com/unindented/electron-installer-windows.git
Cloning into 'electron-installer-windows'...
remote: Counting objects: 380, done.
remote: Compressing objects: 100% (3/3), done.
Receiving objects: 100% (380/380), 6.31 MiB | 736.00 KiB/s, done.

Resolving deltas: 100% (212/212), done.

c:\ElectronProjects>cd electron-installer-windows/example

c:\ElectronProjects\electron-installer-windows\example>npm install
npm WARN deprecated electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
npm WARN deprecated minimatch@2.0.4: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

> electron-prebuilt@1.4.13 postinstall c:\ElectronProjects\electron-installer-windows\example\node_modules\electron-prebuilt
> node install.js

poopie@0.0.1 c:\ElectronProjects\electron-installer-windows\example
+-- electron-installer-windows@0.2.0
| +-- asar@0.9.1
| | +-- chromium-pickle-js@0.1.0
| | +-- commander@2.3.0
| | +-- cuint@0.1.5
| | +-- glob@5.0.15
| | +-- minimatch@2.0.4
| | | `-- brace-expansion@1.1.6
| | |   +-- balanced-match@0.4.2
| | |   `-- concat-map@0.0.1
| | +-- mkdirp@0.5.1
| | | `-- minimist@0.0.8
| | `-- mksnapshot@0.1.0
| |   +-- decompress-zip@0.1.0
| |   | +-- binary@0.3.0
| |   | | +-- buffers@0.1.1
| |   | | `-- chainsaw@0.1.0
| |   | |   `-- traverse@0.3.9
| |   | +-- graceful-fs@3.0.11
| |   | | `-- natives@1.1.0
| |   | +-- mkpath@0.1.0
| |   | +-- nopt@3.0.6
| |   | | `-- abbrev@1.0.9
| |   | +-- q@1.4.1
| |   | +-- readable-stream@1.1.14
| |   | | `-- isarray@0.0.1
| |   | `-- touch@0.0.3
| |   |   `-- nopt@1.0.10
| |   +-- fs-extra@0.18.2
| |   `-- request@2.55.0
| |     +-- aws-sign2@0.5.0
| |     +-- bl@0.9.5
| |     | `-- readable-stream@1.0.34
| |     +-- caseless@0.9.0
| |     +-- combined-stream@0.0.7
| |     | `-- delayed-stream@0.0.5
| |     +-- forever-agent@0.6.1
| |     +-- form-data@0.2.0
| |     | `-- async@0.9.2
| |     +-- har-validator@1.8.0
| |     | +-- bluebird@2.11.0
| |     | +-- chalk@1.1.3
| |     | | +-- ansi-styles@2.2.1
| |     | | +-- escape-string-regexp@1.0.5
| |     | | +-- has-ansi@2.0.0
| |     | | `-- supports-color@2.0.0
| |     | +-- commander@2.9.0
| |     | `-- is-my-json-valid@2.15.0
| |     |   +-- generate-function@2.0.0
| |     |   +-- generate-object-property@1.2.0
| |     |   | `-- is-property@1.0.2
| |     |   +-- jsonpointer@4.0.1
| |     |   `-- xtend@4.0.1
| |     +-- hawk@2.3.1
| |     | +-- boom@2.10.1
| |     | +-- cryptiles@2.0.5
| |     | +-- hoek@2.16.3
| |     | `-- sntp@1.0.9
| |     +-- http-signature@0.10.1
| |     | +-- asn1@0.1.11
| |     | +-- assert-plus@0.1.5
| |     | `-- ctype@0.5.3
| |     +-- isstream@0.1.2
| |     +-- json-stringify-safe@5.0.1
| |     +-- mime-types@2.0.14
| |     | `-- mime-db@1.12.0
| |     +-- node-uuid@1.4.7
| |     +-- oauth-sign@0.6.0
| |     +-- qs@2.4.2
| |     +-- stringstream@0.0.5
| |     +-- tough-cookie@2.3.2
| |     | `-- punycode@1.4.1
| |     `-- tunnel-agent@0.4.3
| +-- async@1.5.2
| +-- debug@2.6.0
| | `-- ms@0.7.2
| +-- fs-extra@0.26.7
| | +-- graceful-fs@4.1.11
| | +-- jsonfile@2.4.0
| | | `-- graceful-fs@4.1.11
| | +-- klaw@1.3.1
| | | `-- graceful-fs@4.1.11
| | `-- path-is-absolute@1.0.1
| +-- glob@6.0.4
| | +-- inflight@1.0.6
| | | `-- wrappy@1.0.2
| | +-- inherits@2.0.3
| | `-- once@1.4.0
| +-- lodash@4.17.4
| +-- temp@0.8.3
| | +-- os-tmpdir@1.0.2
| | `-- rimraf@2.2.8
| `-- yargs@3.32.0
|   +-- camelcase@2.1.1
|   `-- window-size@0.1.4
+-- electron-packager@8.5.1
| +-- asar@0.12.4
| | +-- chromium-pickle-js@0.2.0
| | +-- commander@2.9.0
| | | `-- graceful-readlink@1.0.1
| | +-- cuint@0.2.2
| | +-- minimatch@3.0.3
| | +-- mksnapshot@0.3.0
| | | +-- decompress-zip@0.3.0
| | | `-- fs-extra@0.26.7
| | `-- tmp@0.0.28
| +-- electron-download@3.3.0
| | +-- fs-extra@0.30.0
| | | `-- graceful-fs@4.1.11
| | +-- home-path@1.0.3
| | +-- minimist@1.2.0
| | +-- nugget@2.0.1
| | | +-- minimist@1.2.0
| | | +-- pretty-bytes@1.0.4
| | | | +-- get-stdin@4.0.1
| | | | `-- meow@3.7.0
| | | |   +-- camelcase-keys@2.1.0
| | | |   +-- loud-rejection@1.6.0
| | | |   | +-- currently-unhandled@0.4.1
| | | |   | | `-- array-find-index@1.0.2
| | | |   | `-- signal-exit@3.0.2
| | | |   +-- map-obj@1.0.1
| | | |   +-- minimist@1.2.0
| | | |   +-- object-assign@4.1.1
| | | |   +-- redent@1.0.0
| | | |   | +-- indent-string@2.1.0
| | | |   | | `-- repeating@2.0.1
| | | |   | |   `-- is-finite@1.0.2
| | | |   | `-- strip-indent@1.0.1
| | | |   `-- trim-newlines@1.0.0
| | | +-- progress-stream@1.2.0
| | | | +-- speedometer@0.1.4
| | | | `-- through2@0.2.3
| | | |   `-- xtend@2.1.2
| | | |     `-- object-keys@0.4.0
| | | +-- single-line-log@1.1.2
| | | `-- throttleit@0.0.2
| | +-- path-exists@2.1.0
| | | `-- pinkie-promise@2.0.1
| | |   `-- pinkie@2.0.4
| | +-- rc@1.1.6
| | | +-- deep-extend@0.4.1
| | | +-- ini@1.3.4
| | | +-- minimist@1.2.0
| | | `-- strip-json-comments@1.0.4
| | `-- sumchecker@1.3.0
| |   `-- es6-promise@4.0.5
| +-- electron-osx-sign@0.4.3
| | +-- bluebird@3.4.7
| | +-- compare-version@0.1.2
| | +-- isbinaryfile@3.0.2
| | +-- minimist@1.2.0
| | `-- tempfile@1.1.1
| |   `-- uuid@2.0.3
| +-- extract-zip@1.6.0
| | +-- concat-stream@1.5.0
| | | +-- readable-stream@2.0.6
| | | | +-- core-util-is@1.0.2
| | | | +-- isarray@1.0.0
| | | | +-- process-nextick-args@1.0.7
| | | | +-- string_decoder@0.10.31
| | | | `-- util-deprecate@1.0.2
| | | `-- typedarray@0.0.6
| | +-- debug@0.7.4
| | +-- mkdirp@0.5.0
| | `-- yauzl@2.4.1
| |   `-- fd-slicer@1.0.1
| |     `-- pend@1.2.0
| +-- fs-extra@1.0.0
| | `-- graceful-fs@4.1.11
| +-- get-package-info@1.0.0
| | +-- bluebird@3.4.7
| | +-- lodash.get@4.4.2
| | `-- read-pkg-up@2.0.0
| |   +-- find-up@2.1.0
| |   | `-- locate-path@2.0.0
| |   |   +-- p-locate@2.0.0
| |   |   | `-- p-limit@1.1.0
| |   |   `-- path-exists@3.0.0
| |   `-- read-pkg@2.0.0
| |     +-- load-json-file@2.0.0
| |     | +-- graceful-fs@4.1.11
| |     | `-- strip-bom@3.0.0
| |     `-- path-type@2.0.0
| +-- minimist@1.2.0
| +-- plist@2.0.1
| | +-- base64-js@1.1.2
| | +-- xmlbuilder@8.2.2
| | `-- xmldom@0.1.27
| +-- rcedit@0.7.0
| +-- resolve@1.2.0
| +-- run-series@1.1.4
| +-- sanitize-filename@1.6.1
| | `-- truncate-utf8-bytes@1.0.2
| |   `-- utf8-byte-length@1.0.4
| `-- semver@5.3.0
+-- electron-prebuilt@1.4.13
+-- fs-plus@2.9.3
| +-- async@0.2.10
| +-- mkdirp@0.3.5
| +-- rimraf@2.2.8
| `-- underscore-plus@1.6.6
|   `-- underscore@1.6.0
+-- rimraf@2.5.4
| `-- glob@7.1.1
|   +-- fs.realpath@1.0.0
|   `-- minimatch@3.0.3
`-- yargs@6.6.0
  +-- camelcase@3.0.0
  +-- cliui@3.2.0
  | +-- strip-ansi@3.0.1
  | | `-- ansi-regex@2.1.1
  | `-- wrap-ansi@2.1.0
  +-- decamelize@1.2.0
  +-- get-caller-file@1.0.2
  +-- os-locale@1.4.0
  | `-- lcid@1.0.0
  |   `-- invert-kv@1.0.0
  +-- read-pkg-up@1.0.1
  | +-- find-up@1.1.2
  | `-- read-pkg@1.1.0
  |   +-- load-json-file@1.1.0
  |   | +-- graceful-fs@4.1.11
  |   | +-- parse-json@2.2.0
  |   | | `-- error-ex@1.3.0
  |   | |   `-- is-arrayish@0.2.1
  |   | +-- pify@2.3.0
  |   | `-- strip-bom@2.0.0
  |   |   `-- is-utf8@0.2.1
  |   +-- normalize-package-data@2.3.5
  |   | +-- hosted-git-info@2.1.5
  |   | +-- is-builtin-module@1.0.0
  |   | | `-- builtin-modules@1.1.1
  |   | `-- validate-npm-package-license@3.0.1
  |   |   +-- spdx-correct@1.0.2
  |   |   | `-- spdx-license-ids@1.2.2
  |   |   `-- spdx-expression-parse@1.0.4
  |   `-- path-type@1.1.0
  |     `-- graceful-fs@4.1.11
  +-- require-directory@2.1.1
  +-- require-main-filename@1.0.1
  +-- set-blocking@2.0.0
  +-- string-width@1.0.2
  | +-- code-point-at@1.1.0
  | `-- is-fullwidth-code-point@1.0.0
  |   `-- number-is-nan@1.0.1
  +-- which-module@1.0.0
  +-- y18n@3.2.1
  `-- yargs-parser@4.2.1
    `-- camelcase@3.0.0


c:\ElectronProjects\electron-installer-windows\example>set DEBUG='electron-installer-windows'

c:\ElectronProjects\electron-installer-windows\example>npm run build

> poopie@0.0.1 build c:\ElectronProjects\electron-installer-windows\example
> npm run clean && npm run exe32 && npm run set32 && npm run exe64 && npm run set64


> poopie@0.0.1 clean c:\ElectronProjects\electron-installer-windows\example
> rimraf dist


> poopie@0.0.1 exe32 c:\ElectronProjects\electron-installer-windows\example
> electron-packager . poopie --platform win32 --arch ia32 --out dist/ --ignore "(dist|node_modules/electron.*)" --icon resources/Icon.ico

Packaging app for platform win32 ia32 using electron v1.4.13
Wrote new app to dist\poopie-win32-ia32

> poopie@0.0.1 set32 c:\ElectronProjects\electron-installer-windows\example
> electron-installer-windows --src dist/poopie-win32-ia32/ --dest dist/installers/ia32/ --config config.json

Creating package (this may take a while)
Error: Error releasifying package: Error executing file (4294967295):
c:\ElectronProjects\electron-installer-windows\example\node_modules\electron-installer-windows\vendor\squirrel\Squirrel.com --releasify C:/Users/John/AppData/Local/Temp/electron-11715-5844-1xl8wlm.0fhtulerk9/poopie_0.0.1/nuget/poopie.0.0.1.nupkg --releaseDir C:\Users\John\AppData\Local\Temp\electron-11715-5844-1xl8wlm.0fhtulerk9\poopie_0.0.1\squirrel --setupIcon c:\ElectronProjects\electron-installer-windows\example\resources\Icon.ico --loadingGif c:\ElectronProjects\electron-installer-windows\example\node_modules\electron-installer-windows\resources\animation.gif
System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to modify resources, command invoked was: 'c:\ElectronProjects\electron-installer-windows\example\node_modules\electron-installer-windows\vendor\squirrel\rcedit.exe "C:\Users\John\AppData\Local\Temp\electron-11715-5844-1xl8wlm.0fhtulerk9\poopie_0.0.1\squirrel\Setup.exe" --set-version-string "CompanyName" "Daniel Perez Alvarez" --set-version-string "LegalCopyright" "Copyright � 2017 Daniel Perez Alvarez" --set-version-string "FileDescription" "An example app, built with Electron." --set-version-string "ProductName" "An example app, built with Electron." --set-file-version 0.0.1 --set-product-version 0.0.1 --set-icon "c:\ElectronProjects\electron-installer-windows\example\resources\Icon.ico"'

Output was:

   at Squirrel.Update.Program.<setPEVersionInfoAndIcon>d__17.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.Update.Program.<>c__DisplayClass9_0.<Releasify>b__10()
   at Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()
   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   at Squirrel.Utility.Retry(Action block, Int32 retries)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Failed to modify resources, command invoked was: 'c:\ElectronProjects\electron-installer-windows\example\node_modules\electron-installer-windows\vendor\squirrel\rcedit.exe "C:\Users\John\AppData\Local\Temp\electron-11715-5844-1xl8wlm.0fhtulerk9\poopie_0.0.1\squirrel\Setup.exe" --set-version-string "CompanyName" "Daniel Perez Alvarez" --set-version-string "LegalCopyright" "Copyright � 2017 Daniel Perez Alvarez" --set-version-string "FileDescription" "An example app, built with Electron." --set-version-string "ProductName" "An example app, built with Electron." --set-file-version 0.0.1 --set-product-version 0.0.1 --set-icon "c:\ElectronProjects\electron-installer-windows\example\resources\Icon.ico"'

Output was:

   at Squirrel.Update.Program.<setPEVersionInfoAndIcon>d__17.MoveNext()<---


    at c:\ElectronProjects\electron-installer-windows\example\node_modules\electron-installer-windows\src\installer.js:360:21
    at ChildProcess.<anonymous> (c:\ElectronProjects\electron-installer-windows\example\node_modules\electron-installer-windows\src\installer.js:62:5)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) 'Error: Error releasifying package: Error executing file (4294967295): \nc:\\ElectronProjects\\electron-installer-windows\\example\\node_modules\\electron-installer-windows\\vendor\\squirrel\\Squirrel.com --releasify C:/Users/John/AppData/Local/Temp/electron-11715-5844-1xl8wlm.0fhtulerk9/poopie_0.0.1/nuget/poopie.0.0.1.nupkg --releaseDir C:\\Users\\John\\AppData\\Local\\Temp\\electron-11715-5844-1xl8wlm.0fhtulerk9\\poopie_0.0.1\\squirrel --setupIcon c:\\ElectronProjects\\electron-installer-windows\\example\\resources\\Icon.ico --loadingGif c:\\ElectronProjects\\electron-installer-windows\\example\\node_modules\\electron-installer-windows\\resources\\animation.gif\nSystem.AggregateException: One or more errors occurred. ---> System.Exception: Failed to modify resources, command invoked was: \'c:\\ElectronProjects\\electron-installer-windows\\example\\node_modules\\electron-installer-windows\\vendor\\squirrel\\rcedit.exe "C:\\Users\\John\\AppData\\Local\\Temp\\electron-11715-5844-1xl8wlm.0fhtulerk9\\poopie_0.0.1\\squirrel\\Setup.exe" --set-version-string "CompanyName" "Daniel Perez Alvarez" --set-version-string "LegalCopyright" "Copyright � 2017 Daniel Perez Alvarez" --set-version-string "FileDescription" "An example app, built with Electron." --set-version-string "ProductName" "An example app, built with Electron." --set-file-version 0.0.1 --set-product-version 0.0.1 --set-icon "c:\\ElectronProjects\\electron-installer-windows\\example\\resources\\Icon.ico"\'\n\nOutput was:\n\r\n   at Squirrel.Update.Program.<setPEVersionInfoAndIcon>d__17.MoveNext()\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at Squirrel.Update.Program.<>c__DisplayClass9_0.<Releasify>b__10()\r\n   at Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()\r\n   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)\r\n   at Squirrel.Utility.Retry(Action block, Int32 retries)\r\n   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi)\r\n   at Squirrel.Update.Program.executeCommandLine(String[] args)\r\n   at Squirrel.Update.Program.main(String[] args)\r\n   at Squirrel.Update.Program.Main(String[] args)\r\n---> (Inner Exception #0) System.Exception: Failed to modify resources, command invoked was: \'c:\\ElectronProjects\\electron-installer-windows\\example\\node_modules\\electron-installer-windows\\vendor\\squirrel\\rcedit.exe "C:\\Users\\John\\AppData\\Local\\Temp\\electron-11715-5844-1xl8wlm.0fhtulerk9\\poopie_0.0.1\\squirrel\\Setup.exe" --set-version-string "CompanyName" "Daniel Perez Alvarez" --set-version-string "LegalCopyright" "Copyright � 2017 Daniel Perez Alvarez" --set-version-string "FileDescription" "An example app, built with Electron." --set-version-string "ProductName" "An example app, built with Electron." --set-file-version 0.0.1 --set-product-version 0.0.1 --set-icon "c:\\ElectronProjects\\electron-installer-windows\\example\\resources\\Icon.ico"\'\n\nOutput was:\n\r\n   at Squirrel.Update.Program.<setPEVersionInfoAndIcon>d__17.MoveNext()<---\r\n\r\n\n    at c:\\ElectronProjects\\electron-installer-windows\\example\\node_modules\\electron-installer-windows\\src\\installer.js:360:21\n    at ChildProcess.<anonymous> (c:\\ElectronProjects\\electron-installer-windows\\example\\node_modules\\electron-installer-windows\\src\\installer.js:62:5)\n    at emitTwo (events.js:111:20)\n    at ChildProcess.emit (events.js:191:7)\n    at maybeClose (internal/child_process.js:877:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)'

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "set32"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! poopie@0.0.1 set32: `electron-installer-windows --src dist/poopie-win32-ia32/ --dest dist/installers/ia32/ --config config.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the poopie@0.0.1 set32 script 'electron-installer-windows --src dist/poopie-win32-ia32/ --dest dist/installers/ia32/ --config config.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the poopie package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-installer-windows --src dist/poopie-win32-ia32/ --dest dist/installers/ia32/ --config config.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs poopie
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls poopie
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\ElectronProjects\electron-installer-windows\example\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! poopie@0.0.1 build: `npm run clean && npm run exe32 && npm run set32 && npm run exe64 && npm run set64`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the poopie@0.0.1 build script 'npm run clean && npm run exe32 && npm run set32 && npm run exe64 && npm run set64'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the poopie package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run exe32 && npm run set32 && npm run exe64 && npm run set64
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs poopie
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls poopie
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\ElectronProjects\electron-installer-windows\example\npm-debug.log

c:\ElectronProjects\electron-installer-windows\example>
```

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
See above

**What did you expect to happen?**
No errors

**What actually happened?**
See above

**Comment by unindented** [comment]
Never seen it before. Sounds like Squirrel.Windows is erroring out for some reason, but the stack trace doesn't give much info.

**Comment by belltown** [comment]
I think it has something to do with the version of rcedit.exe that it's using. I was able to get it working by copying the version from https://github.com/atom/node-rcedit/raw/master/bin/rcedit.exe to \electron-installer-windows\example\node_modules\electron-installer-windows\vendor\squirrel\rcedit.exe, as mentioned in this issue: https://github.com/Squirrel/Squirrel.Windows/issues/488

**Comment by roman0x58** [comment]
I have the same problem on Windows 10 Home, workaround with rcedit.exe is helpful

**Comment by FranciscoKnebel** [comment]
Confirmed here too, problem fixed with replacing rcedit.exe version. Thank you, @belltown .

**Comment by stepanic** [comment]
For me @belltown workaround was not working, I tried on macOS Sierra 10.12.3 and on Windows 10

This is error:
```
$ electron-installer-windows --src app-builds/mediawall-desktop-win32-ia32/ --dest app-builds/installers/
Creating package (this may take a while)
Error: Error releasifying package: Error executing file (255):
mono /Users/matijastepanic/.nvm/versions/node/v7.10.0/lib/node_modules/electron-installer-windows/vendor/squirrel/Squirrel-Mono.exe --releasify /var/folders/br/7wxxdfyd201gqq2n192zj5bm0000gn/T/electron-117521-10641-ck3hc7.rcx8hncdi/mediawall-desktop_1.5.0/nuget/mediawall-desktop.1.5.0.nupkg --releaseDir /var/folders/br/7wxxdfyd201gqq2n192zj5bm0000gn/T/electron-117521-10641-ck3hc7.rcx8hncdi/mediawall-desktop_1.5.0/squirrel --setupIcon /Users/matijastepanic/.nvm/versions/node/v7.10.0/lib/node_modules/electron-installer-windows/resources/icon.ico --loadingGif /Users/matijastepanic/.nvm/versions/node/v7.10.0/lib/node_modules/electron-installer-windows/resources/animation.gif
System.InvalidOperationException: The input package file /var/folders/br/7wxxdfyd201gqq2n192zj5bm0000gn/T/electron-117521-10641-ck3hc7.rcx8hncdi/mediawall-desktop_1.5.0/squirrel/mediawall-desktop.1.5.0.nupkg targets no platform and cannot be transformed into a release package.
  at Squirrel.ReleasePackage.CreateReleasePackage (System.String outputFile, System.String packagesRootDir, System.Func`2[T,TResult] releaseNotesProcessor, System.Action`1[T] contentsPostProcessHook) [0x000ad] in <a738fa86ffa346549b0ac27411465911>:0
  at Squirrel.Update.Program.Releasify (System.String package, System.String targetDir, System.String packagesDir, System.String bootstrapperExe, System.String backgroundGif, System.String signingOpts, System.String baseUrl, System.String setupIcon, System.Boolean generateMsi) [0x00208] in <a738fa86ffa346549b0ac27411465911>:0
  at Squirrel.Update.Program.executeCommandLine (System.String[] args) [0x00439] in <a738fa86ffa346549b0ac27411465911>:0
  at Squirrel.Update.Program.main (System.String[] args) [0x00082] in <a738fa86ffa346549b0ac27411465911>:0
  at Squirrel.Update.Program.Main (System.String[] args) [0x00006] in <a738fa86ffa346549b0ac27411465911>:0

    at /Users/matijastepanic/.nvm/versions/node/v7.10.0/lib/node_modules/electron-installer-windows/src/installer.js:360:21
    at ChildProcess.<anonymous> (/Users/matijastepanic/.nvm/versions/node/v7.10.0/lib/node_modules/electron-installer-windows/src/installer.js:62:5)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) 'Error: Error releasifying package: Error executing file (255): \nmono /Users/matijastepanic/.nvm/versions/node/v7.10.0/lib/node_modules/electron-installer-windows/vendor/squirrel/Squirrel-Mono.exe --releasify /var/folders/br/7wxxdfyd201gqq2n192zj5bm0000gn/T/electron-117521-10641-ck3hc7.rcx8hncdi/mediawall-desktop_1.5.0/nuget/mediawall-desktop.1.5.0.nupkg --releaseDir /var/folders/br/7wxxdfyd201gqq2n192zj5bm0000gn/T/electron-117521-10641-ck3hc7.rcx8hncdi/mediawall-desktop_1.5.0/squirrel --setupIcon /Users/matijastepanic/.nvm/versions/node/v7.10.0/lib/node_modules/electron-installer-windows/resources/icon.ico --loadingGif /Users/matijastepanic/.nvm/versions/node/v7.10.0/lib/node_modules/electron-installer-windows/resources/animation.gif\nSystem.InvalidOperationException: The input package file /var/folders/br/7wxxdfyd201gqq2n192zj5bm0000gn/T/electron-117521-10641-ck3hc7.rcx8hncdi/mediawall-desktop_1.5.0/squirrel/mediawall-desktop.1.5.0.nupkg targets no platform and cannot be transformed into a release package.\n  at Squirrel.ReleasePackage.CreateReleasePackage (System.String outputFile, System.String packagesRootDir, System.Func`2[T,TResult] releaseNotesProcessor, System.Action`1[T] contentsPostProcessHook) [0x000ad] in <a738fa86ffa346549b0ac27411465911>:0 \n  at Squirrel.Update.Program.Releasify (System.String package, System.String targetDir, System.String packagesDir, System.String bootstrapperExe, System.String backgroundGif, System.String signingOpts, System.String baseUrl, System.String setupIcon, System.Boolean generateMsi) [0x00208] in <a738fa86ffa346549b0ac27411465911>:0 \n  at Squirrel.Update.Program.executeCommandLine (System.String[] args) [0x00439] in <a738fa86ffa346549b0ac27411465911>:0 \n  at Squirrel.Update.Program.main (System.String[] args) [0x00082] in <a738fa86ffa346549b0ac27411465911>:0 \n  at Squirrel.Update.Program.Main (System.String[] args) [0x00006] in <a738fa86ffa346549b0ac27411465911>:0 \n\n    at /Users/matijastepanic/.nvm/versions/node/v7.10.0/lib/node_modules/electron-installer-windows/src/installer.js:360:21\n    at ChildProcess.<anonymous> (/Users/matijastepanic/.nvm/versions/node/v7.10.0/lib/node_modules/electron-installer-windows/src/installer.js:62:5)\n    at emitTwo (events.js:111:20)\n    at ChildProcess.emit (events.js:194:7)\n    at maybeClose (internal/child_process.js:899:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)'
```

**Comment by unindented** [comment]
@stepanic Have you tried running on a Windows machine?

**Comment by stepanic** [comment]
@unindented yes, on Macbook Pro and on HP Omen (Windows 10)

**Comment by unindented** [comment]
@stepanic can you paste the error from Windows? The one you pasted above is showing a problem with Mono, which wouldn't happen on Windows...

**Comment by HabibulHH** [comment]
do you have any solution for a problem?

**Comment by etiennea** [comment]
Also getting this error on mac

`Error: Error releasifying package: Error executing file (255): 
mono /Users/etienne/Github/alpha/express/public/app3/node_modules/electron-installer-windows/vendor/squirrel/Squirrel-Mono.exe --releasify /var/folders/s2/lt6js09s72j9m7gr57yq08r80000gn/T/electron-11782-65076-1i7ixpy.ghz7/AlphaPlay_3.0.0/nuget/AlphaPlay.3.0.0.nupkg --releaseDir /var/folders/s2/lt6js09s72j9m7gr57yq08r80000gn/T/electron-11782-65076-1i7ixpy.ghz7/AlphaPlay_3.0.0/squirrel --setupIcon /Users/etienne/Github/alpha/express/public/app3/node_modules/electron-installer-windows/resources/icon.ico --loadingGif /Users/etienne/Github/alpha/express/public/app3/node_modules/electron-installer-windows/resources/animation.gif
System.InvalidOperationException: The input package file /var/folders/s2/lt6js09s72j9m7gr57yq08r80000gn/T/electron-11782-65076-1i7ixpy.ghz7/AlphaPlay_3.0.0/squirrel/AlphaPlay.3.0.0.nupkg targets no platform and cannot be transformed into a release package.
  at Squirrel.ReleasePackage.CreateReleasePackage `

**Comment by unindented** [comment]
Could be an issue with mono. Try running on Windows.

**Comment by fcastilloec** [comment]
All these errors should be fixed with the latest release. Please try that one, and if you find another error feel free to open a new issue
