### ISSUE TITLE
??????????

### ISSUE THREAD

**Issue by nesfe** [unindented/electron-installer-windows#204]
λ electron-installer-windows --src builds\aladin2.0-win32-x64\ --dest builds\
Creating package (this may take a while)
Error: Error creating package: Error executing file (1):
C:\Program Files\nodejs\node_modules\electron-installer-windows\vendor\nuget\NuGet.exe pack C:\Users\lukang\AppData\Local\Temp\electron-117411-13856-b8eiiq.f987meipb9\aladin2.0_0.0.0\nuget\aladin2.0.nuspec -BasePath C:\Users\lukang\AppData\Local\Temp\electron-117411-13856-b8eiiq.f987meipb9\aladin2.0_0.0.0\aladin2.0 -OutputDirectory C:\Users\lukang\AppData\Local\Temp\electron-117411-13856-b8eiiq.f987meipb9\aladin2.0_0.0.0\nuget -NoDefaultExcludes
��Ч�� URI: δ��ȷ�� URI �ĸ�ʽ��

    at C:\Program Files\nodejs\node_modules\electron-installer-windows\src\installer.js:273:21
    at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\electron-installer-windows\src\installer.js:62:5)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5) 'Error: Error creating package: Error executing file (1): \nC:\\Program Files\\nodejs\\node_modules\\electron-installer-windows\\vendor\\nuget\\NuGet.exe pack C:\\Users\\lukang\\AppData\\Local\\Temp\\electron-117411-13856-b8eiiq.f987meipb9\\aladin2.0_0.0.0\\nuget\\aladin2.0.nuspec -BasePath C:\\Users\\lukang\\AppData\\Local\\Temp\\electron-117411-13856-b8eiiq.f987meipb9\\aladin2.0_0.0.0\\aladin2.0 -OutputDirectory C:\\Users\\lukang\\AppData\\Local\\Temp\\electron-117411-13856-b8eiiq.f987meipb9\\aladin2.0_0.0.0\\nuget -NoDefaultExcludes\n��Ч�� URI: δ��ȷ�� URI �ĸ�ʽ��\r\n\n    at C:\\Program Files\\nodejs\\node_modules\\electron-installer-windows\\src\\installer.js:273:21\n    at ChildProcess.<anonymous> (C:\\Program Files\\nodejs\\node_modules\\electron-installer-windows\\src\\installer.js:62:5)\n    at emitTwo (events.js:111:20)\n    at ChildProcess.emit (events.js:191:7)\n    at maybeClose (internal/child_process.js:850:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)'

**Comment by unindented** [comment]
Fill out the template.
