### ISSUE TITLE
Problems generating windows installer

### ISSUE THREAD

**Issue by jegj** [unindented/electron-installer-windows#218]
**What version of `electron-installer-windows` are you using?**
0.2.0

**What version of `node` and `npm` are you using?**
8.1.3 & 5.1.0
**What operating system are you using?**
Ubuntu 16.04
**Can you compile the [example app](https://github.com/unindented/electron-installer-windows/tree/master/example) successfully?**
No
**If not, paste here the output of the following commands:**

```
Packaging app for platform win32 ia32 using electron v1.4.13
Wrote new app to dist/poopie-win32-ia32

> poopie@0.0.1 set32 /home/javier/projects/electron-installer-windows/example
> electron-installer-windows --src dist/poopie-win32-ia32/ --dest dist/installers/ia32/ --config config.json

Creating package (this may take a while)
  electron-installer-windows Reading package metadata from dist/poopie-win32-ia32/resources/app/package.json +0ms
  electron-installer-windows Creating package with options
  electron-installer-windows {
  electron-installer-windows   "src": "dist/poopie-win32-ia32/",
  electron-installer-windows   "dest": "dist/installers/ia32/",
  electron-installer-windows   "config": "config.json",
  electron-installer-windows   "icon": "resources/Icon.ico",
  electron-installer-windows   "tags": [
  electron-installer-windows     "Utility"
  electron-installer-windows   ],
  electron-installer-windows   "name": "poopie",
  electron-installer-windows   "productName": "poopie",
  electron-installer-windows   "description": "An example app, built with Electron.",
  electron-installer-windows   "productDescription": "An example app, built with Electron.",
  electron-installer-windows   "version": "0.0.1",
  electron-installer-windows   "copyright": "Copyright © 2017 Daniel Perez Alvarez",
  electron-installer-windows   "authors": [
  electron-installer-windows     "Daniel Perez Alvarez"
  electron-installer-windows   ],
  electron-installer-windows   "owners": [
  electron-installer-windows     "Daniel Perez Alvarez"
  electron-installer-windows   ],
  electron-installer-windows   "homepage": "http://unindented.org/",
  electron-installer-windows   "exe": "poopie.exe",
  electron-installer-windows   "animation": "/home/javier/projects/electron-installer-windows/example/node_modules/electron-installer-windows/resources/animation.gif",
  electron-installer-windows   "requireLicenseAcceptance": false,
  electron-installer-windows   "noMsi": false
  electron-installer-windows } +6ms
  electron-installer-windows Creating temporary directory +2ms
  electron-installer-windows Creating subdirectories under /tmp/electron-11784-30523-zi7ahm.1x7se/poopie_0.0.1 +4ms
  electron-installer-windows Creating contents of package +1ms
  electron-installer-windows Creating spec file at /tmp/electron-11784-30523-zi7ahm.1x7se/poopie_0.0.1/nuget/poopie.nuspec +1ms
  electron-installer-windows Generating template from /home/javier/projects/electron-installer-windows/example/node_modules/electron-installer-windows/resources/spec.ejs +0ms
  electron-installer-windows Copying application to /tmp/electron-11784-30523-zi7ahm.1x7se/poopie_0.0.1/poopie +1ms
  electron-installer-windows Generated template from /home/javier/projects/electron-installer-windows/example/node_modules/electron-installer-windows/resources/spec.ejs
  electron-installer-windows <?xml version="1.0" encoding="utf-8"?>
  electron-installer-windows <package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  electron-installer-windows   <metadata>
  electron-installer-windows     <id>poopie</id>
  electron-installer-windows     <title>poopie</title>
  electron-installer-windows     <summary>An example app, built with Electron.</summary>
  electron-installer-windows     <description>An example app, built with Electron.</description>
  electron-installer-windows     <version>0.0.1</version>
  electron-installer-windows     <copyright>Copyright © 2017 Daniel Perez Alvarez</copyright>
  electron-installer-windows     <authors>Daniel Perez Alvarez</authors>
  electron-installer-windows     <owners>Daniel Perez Alvarez</owners>
  electron-installer-windows     <projectUrl>http://unindented.org/</projectUrl>
  electron-installer-windows     
  electron-installer-windows     
  electron-installer-windows     
  electron-installer-windows     <tags>Utility</tags>
  electron-installer-windows   </metadata>
  electron-installer-windows   <files>
  electron-installer-windows     <file src="locales\**" target="lib\net45\locales" />
  electron-installer-windows     <file src="resources\**" target="lib\net45\resources" />
  electron-installer-windows     <file src="*.bin" target="lib\net45" />
  electron-installer-windows     <file src="*.dll" target="lib\net45" />
  electron-installer-windows     <file src="*.pak" target="lib\net45" />
  electron-installer-windows     <file src="Update.exe" target="lib\net45\squirrel.exe" />
  electron-installer-windows     <file src="icudtl.dat" target="lib\net45\icudtl.dat" />
  electron-installer-windows     <file src="LICENSE" target="lib\net45\LICENSE" />
  electron-installer-windows     <file src="poopie.exe" target="lib\net45\poopie.exe" />
  electron-installer-windows   </files>
  electron-installer-windows </package>
  electron-installer-windows  +6ms
  electron-installer-windows Creating package at /tmp/electron-11784-30523-zi7ahm.1x7se/poopie_0.0.1 +276ms
  electron-installer-windows Executing file mono /home/javier/projects/electron-installer-windows/example/node_modules/electron-installer-windows/vendor/nuget/NuGet.exe pack /tmp/electron-11784-30523-zi7ahm.1x7se/poopie_0.0.1/nuget/poopie.nuspec -BasePath /tmp/electron-11784-30523-zi7ahm.1x7se/poopie_0.0.1/poopie -OutputDirectory /tmp/electron-11784-30523-zi7ahm.1x7se/poopie_0.0.1/nuget -NoDefaultExcludes +0ms
  electron-installer-windows Error creating package: Error creating package: Error executing file (SIGABRT): 
  electron-installer-windows mono /home/javier/projects/electron-installer-windows/example/node_modules/electron-installer-windows/vendor/nuget/NuGet.exe pack /tmp/electron-11784-30523-zi7ahm.1x7se/poopie_0.0.1/nuget/poopie.nuspec -BasePath /tmp/electron-11784-30523-zi7ahm.1x7se/poopie_0.0.1/poopie -OutputDirectory /tmp/electron-11784-30523-zi7ahm.1x7se/poopie_0.0.1/nuget -NoDefaultExcludes
  electron-installer-windows Stacktrace:
  electron-installer-windows 
  electron-installer-windows 
  electron-installer-windows Native stacktrace:
  electron-installer-windows 
  electron-installer-windows 	mono() [0x49ff2f]
  electron-installer-windows 	/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7f8ee29fc390]
  electron-installer-windows 	/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38) [0x7f8ee2656428]
  electron-installer-windows 	/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7f8ee265802a]
  electron-installer-windows 	mono() [0x630409]
  electron-installer-windows 	mono() [0x63069c]
  electron-installer-windows 	mono() [0x630833]
  electron-installer-windows 	mono() [0x54357a]
  electron-installer-windows 	mono(mono_class_from_typeref_checked+0x223) [0x524c63]
  electron-installer-windows 	mono() [0x5234ad]
  electron-installer-windows 	mono(mono_metadata_parse_mh_full+0x497) [0x5620b7]
  electron-installer-windows 	mono() [0x433fd6]
  electron-installer-windows 	mono() [0x500b39]
  electron-installer-windows 	mono() [0x501fbd]
  electron-installer-windows 	mono() [0x425db6]
  electron-installer-windows 	mono() [0x426749]
  electron-installer-windows 	mono(mono_runtime_invoke+0x3d) [0x5ac68d]
  electron-installer-windows 	mono(mono_runtime_exec_main+0x10d) [0x5aea1d]
  electron-installer-windows 	mono(mono_main+0x1177) [0x476967]
  electron-installer-windows 	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f8ee2641830]
  electron-installer-windows 	mono(_start+0x29) [0x422e79]
  electron-installer-windows 
  electron-installer-windows Debug info from gdb:
  electron-installer-windows 
  electron-installer-windows [New LWP 30534]
  electron-installer-windows [New LWP 30535]
  electron-installer-windows [Thread debugging using libthread_db enabled]
  electron-installer-windows Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
  electron-installer-windows 0x00007f8ee29fbf7b in __waitpid (pid=30536, stat_loc=0x7ffc036bd43c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
  electron-installer-windows 29	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  electron-installer-windows   Id   Target Id         Frame 
  electron-installer-windows * 1    Thread 0x7f8ee3513780 (LWP 30533) "mono" 0x00007f8ee29fbf7b in __waitpid (pid=30536, stat_loc=0x7ffc036bd43c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
  electron-installer-windows   2    Thread 0x7f8ee1bff700 (LWP 30534) "mono" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  electron-installer-windows   3    Thread 0x7f8edfb15700 (LWP 30535) "Finalizer" 0x00007f8ee29fa827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x956820) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  electron-installer-windows 
  electron-installer-windows Thread 3 (Thread 0x7f8edfb15700 (LWP 30535)):
  electron-installer-windows #0  0x00007f8ee29fa827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x956820) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  electron-installer-windows #1  do_futex_wait (sem=sem@entry=0x956820, abstime=0x0) at sem_waitcommon.c:111
  electron-installer-windows #2  0x00007f8ee29fa8d4 in __new_sem_wait_slow (sem=0x956820, abstime=0x0) at sem_waitcommon.c:181
  electron-installer-windows #3  0x00007f8ee29fa97a in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29
  electron-installer-windows #4  0x0000000000622e06 in mono_sem_wait ()
  electron-installer-windows #5  0x00000000005a5742 in ?? ()
  electron-installer-windows #6  0x0000000000587b2b in ?? ()
  electron-installer-windows #7  0x0000000000629a8c in ?? ()
  electron-installer-windows #8  0x00007f8ee29f26ba in start_thread (arg=0x7f8edfb15700) at pthread_create.c:333
  electron-installer-windows #9  0x00007f8ee27283dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
  electron-installer-windows 
  electron-installer-windows Thread 2 (Thread 0x7f8ee1bff700 (LWP 30534)):
  electron-installer-windows #0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  electron-installer-windows #1  0x00000000005fdcdb in ?? ()
  electron-installer-windows #2  0x00007f8ee29f26ba in start_thread (arg=0x7f8ee1bff700) at pthread_create.c:333
  electron-installer-windows #3  0x00007f8ee27283dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
  electron-installer-windows 
  electron-installer-windows Thread 1 (Thread 0x7f8ee3513780 (LWP 30533)):
  electron-installer-windows #0  0x00007f8ee29fbf7b in __waitpid (pid=30536, stat_loc=0x7ffc036bd43c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
  electron-installer-windows #1  0x00000000004a0006 in ?? ()
  electron-installer-windows #2  <signal handler called>
  electron-installer-windows #3  0x00007f8ee2656428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
  electron-installer-windows #4  0x00007f8ee265802a in __GI_abort () at abort.c:89
  electron-installer-windows #5  0x0000000000630409 in ?? ()
  electron-installer-windows #6  0x000000000063069c in ?? ()
  electron-installer-windows #7  0x0000000000630833 in ?? ()
  electron-installer-windows #8  0x000000000054357a in ?? ()
  electron-installer-windows #9  0x0000000000524c63 in mono_class_from_typeref_checked ()
  electron-installer-windows #10 0x00000000005234ad in ?? ()
  electron-installer-windows #11 0x00000000005620b7 in mono_metadata_parse_mh_full ()
  electron-installer-windows #12 0x0000000000433fd6 in ?? ()
  electron-installer-windows #13 0x0000000000500b39 in ?? ()
  electron-installer-windows #14 0x0000000000501fbd in ?? ()
  electron-installer-windows #15 0x0000000000425db6 in ?? ()
  electron-installer-windows #16 0x0000000000426749 in ?? ()
  electron-installer-windows #17 0x00000000005ac68d in mono_runtime_invoke ()
  electron-installer-windows #18 0x00000000005aea1d in mono_runtime_exec_main ()
  electron-installer-windows #19 0x0000000000476967 in mono_main ()
  electron-installer-windows #20 0x00007f8ee2641830 in __libc_start_main (main=0x422be0, argc=9, argv=0x7ffc036bf2f8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc036bf2e8) at ../csu/libc-start.c:291
  electron-installer-windows #21 0x0000000000422e79 in _start ()
  electron-installer-windows 
  electron-installer-windows =================================================================
  electron-installer-windows Got a SIGABRT while executing native code. This usually indicates
  electron-installer-windows a fatal error in the mono runtime or one of the native libraries 
  electron-installer-windows used by your application.
  electron-installer-windows =================================================================
  electron-installer-windows 
  electron-installer-windows  +914ms
Error: Error creating package: Error executing file (SIGABRT): 
mono /home/javier/projects/electron-installer-windows/example/node_modules/electron-installer-windows/vendor/nuget/NuGet.exe pack /tmp/electron-11784-30523-zi7ahm.1x7se/poopie_0.0.1/nuget/poopie.nuspec -BasePath /tmp/electron-11784-30523-zi7ahm.1x7se/poopie_0.0.1/poopie -OutputDirectory /tmp/electron-11784-30523-zi7ahm.1x7se/poopie_0.0.1/nuget -NoDefaultExcludes
Stacktrace:


Native stacktrace:

	mono() [0x49ff2f]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7f8ee29fc390]
	/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38) [0x7f8ee2656428]
	/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7f8ee265802a]
	mono() [0x630409]
	mono() [0x63069c]
	mono() [0x630833]
	mono() [0x54357a]
	mono(mono_class_from_typeref_checked+0x223) [0x524c63]
	mono() [0x5234ad]
	mono(mono_metadata_parse_mh_full+0x497) [0x5620b7]
	mono() [0x433fd6]
	mono() [0x500b39]
	mono() [0x501fbd]
	mono() [0x425db6]
	mono() [0x426749]
	mono(mono_runtime_invoke+0x3d) [0x5ac68d]
	mono(mono_runtime_exec_main+0x10d) [0x5aea1d]
	mono(mono_main+0x1177) [0x476967]
	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f8ee2641830]
	mono(_start+0x29) [0x422e79]

Debug info from gdb:

[New LWP 30534]
[New LWP 30535]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f8ee29fbf7b in __waitpid (pid=30536, stat_loc=0x7ffc036bd43c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
29	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id         Frame 
* 1    Thread 0x7f8ee3513780 (LWP 30533) "mono" 0x00007f8ee29fbf7b in __waitpid (pid=30536, stat_loc=0x7ffc036bd43c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
  2    Thread 0x7f8ee1bff700 (LWP 30534) "mono" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7f8edfb15700 (LWP 30535) "Finalizer" 0x00007f8ee29fa827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x956820) at ../sysdeps/unix/sysv/linux/futex-internal.h:205

Thread 3 (Thread 0x7f8edfb15700 (LWP 30535)):
#0  0x00007f8ee29fa827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x956820) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x956820, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f8ee29fa8d4 in __new_sem_wait_slow (sem=0x956820, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007f8ee29fa97a in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29
#4  0x0000000000622e06 in mono_sem_wait ()
#5  0x00000000005a5742 in ?? ()
#6  0x0000000000587b2b in ?? ()
#7  0x0000000000629a8c in ?? ()
#8  0x00007f8ee29f26ba in start_thread (arg=0x7f8edfb15700) at pthread_create.c:333
#9  0x00007f8ee27283dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f8ee1bff700 (LWP 30534)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00000000005fdcdb in ?? ()
#2  0x00007f8ee29f26ba in start_thread (arg=0x7f8ee1bff700) at pthread_create.c:333
#3  0x00007f8ee27283dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f8ee3513780 (LWP 30533)):
#0  0x00007f8ee29fbf7b in __waitpid (pid=30536, stat_loc=0x7ffc036bd43c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00000000004a0006 in ?? ()
#2  <signal handler called>
#3  0x00007f8ee2656428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#4  0x00007f8ee265802a in __GI_abort () at abort.c:89
#5  0x0000000000630409 in ?? ()
#6  0x000000000063069c in ?? ()
#7  0x0000000000630833 in ?? ()
#8  0x000000000054357a in ?? ()
#9  0x0000000000524c63 in mono_class_from_typeref_checked ()
#10 0x00000000005234ad in ?? ()
#11 0x00000000005620b7 in mono_metadata_parse_mh_full ()
#12 0x0000000000433fd6 in ?? ()
#13 0x0000000000500b39 in ?? ()
#14 0x0000000000501fbd in ?? ()
#15 0x0000000000425db6 in ?? ()
#16 0x0000000000426749 in ?? ()
#17 0x00000000005ac68d in mono_runtime_invoke ()
#18 0x00000000005aea1d in mono_runtime_exec_main ()
#19 0x0000000000476967 in mono_main ()
#20 0x00007f8ee2641830 in __libc_start_main (main=0x422be0, argc=9, argv=0x7ffc036bf2f8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc036bf2e8) at ../csu/libc-start.c:291
#21 0x0000000000422e79 in _start ()

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================


    at /home/javier/projects/electron-installer-windows/example/node_modules/electron-installer-windows/src/installer.js:273:21
    at ChildProcess.<anonymous> (/home/javier/projects/electron-installer-windows/example/node_modules/electron-installer-windows/src/installer.js:62:5)
    at emitTwo (events.js:130:20)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5) 'Error: Error creating package: Error executing file (SIGABRT): \nmono /home/javier/projects/electron-installer-windows/example/node_modules/electron-installer-windows/vendor/nuget/NuGet.exe pack /tmp/electron-11784-30523-zi7ahm.1x7se/poopie_0.0.1/nuget/poopie.nuspec -BasePath /tmp/electron-11784-30523-zi7ahm.1x7se/poopie_0.0.1/poopie -OutputDirectory /tmp/electron-11784-30523-zi7ahm.1x7se/poopie_0.0.1/nuget -NoDefaultExcludes\nStacktrace:\n\n\nNative stacktrace:\n\n\tmono() [0x49ff2f]\n\t/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7f8ee29fc390]\n\t/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38) [0x7f8ee2656428]\n\t/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7f8ee265802a]\n\tmono() [0x630409]\n\tmono() [0x63069c]\n\tmono() [0x630833]\n\tmono() [0x54357a]\n\tmono(mono_class_from_typeref_checked+0x223) [0x524c63]\n\tmono() [0x5234ad]\n\tmono(mono_metadata_parse_mh_full+0x497) [0x5620b7]\n\tmono() [0x433fd6]\n\tmono() [0x500b39]\n\tmono() [0x501fbd]\n\tmono() [0x425db6]\n\tmono() [0x426749]\n\tmono(mono_runtime_invoke+0x3d) [0x5ac68d]\n\tmono(mono_runtime_exec_main+0x10d) [0x5aea1d]\n\tmono(mono_main+0x1177) [0x476967]\n\t/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f8ee2641830]\n\tmono(_start+0x29) [0x422e79]\n\nDebug info from gdb:\n\n[New LWP 30534]\n[New LWP 30535]\n[Thread debugging using libthread_db enabled]\nUsing host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".\n0x00007f8ee29fbf7b in __waitpid (pid=30536, stat_loc=0x7ffc036bd43c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29\n29\t../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.\n  Id   Target Id         Frame \n* 1    Thread 0x7f8ee3513780 (LWP 30533) "mono" 0x00007f8ee29fbf7b in __waitpid (pid=30536, stat_loc=0x7ffc036bd43c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29\n  2    Thread 0x7f8ee1bff700 (LWP 30534) "mono" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185\n  3    Thread 0x7f8edfb15700 (LWP 30535) "Finalizer" 0x00007f8ee29fa827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x956820) at ../sysdeps/unix/sysv/linux/futex-internal.h:205\n\nThread 3 (Thread 0x7f8edfb15700 (LWP 30535)):\n#0  0x00007f8ee29fa827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x956820) at ../sysdeps/unix/sysv/linux/futex-internal.h:205\n#1  do_futex_wait (sem=sem@entry=0x956820, abstime=0x0) at sem_waitcommon.c:111\n#2  0x00007f8ee29fa8d4 in __new_sem_wait_slow (sem=0x956820, abstime=0x0) at sem_waitcommon.c:181\n#3  0x00007f8ee29fa97a in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29\n#4  0x0000000000622e06 in mono_sem_wait ()\n#5  0x00000000005a5742 in ?? ()\n#6  0x0000000000587b2b in ?? ()\n#7  0x0000000000629a8c in ?? ()\n#8  0x00007f8ee29f26ba in start_thread (arg=0x7f8edfb15700) at pthread_create.c:333\n#9  0x00007f8ee27283dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109\n\nThread 2 (Thread 0x7f8ee1bff700 (LWP 30534)):\n#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185\n#1  0x00000000005fdcdb in ?? ()\n#2  0x00007f8ee29f26ba in start_thread (arg=0x7f8ee1bff700) at pthread_create.c:333\n#3  0x00007f8ee27283dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109\n\nThread 1 (Thread 0x7f8ee3513780 (LWP 30533)):\n#0  0x00007f8ee29fbf7b in __waitpid (pid=30536, stat_loc=0x7ffc036bd43c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29\n#1  0x00000000004a0006 in ?? ()\n#2  <signal handler called>\n#3  0x00007f8ee2656428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54\n#4  0x00007f8ee265802a in __GI_abort () at abort.c:89\n#5  0x0000000000630409 in ?? ()\n#6  0x000000000063069c in ?? ()\n#7  0x0000000000630833 in ?? ()\n#8  0x000000000054357a in ?? ()\n#9  0x0000000000524c63 in mono_class_from_typeref_checked ()\n#10 0x00000000005234ad in ?? ()\n#11 0x00000000005620b7 in mono_metadata_parse_mh_full ()\n#12 0x0000000000433fd6 in ?? ()\n#13 0x0000000000500b39 in ?? ()\n#14 0x0000000000501fbd in ?? ()\n#15 0x0000000000425db6 in ?? ()\n#16 0x0000000000426749 in ?? ()\n#17 0x00000000005ac68d in mono_runtime_invoke ()\n#18 0x00000000005aea1d in mono_runtime_exec_main ()\n#19 0x0000000000476967 in mono_main ()\n#20 0x00007f8ee2641830 in __libc_start_main (main=0x422be0, argc=9, argv=0x7ffc036bf2f8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc036bf2e8) at ../csu/libc-start.c:291\n#21 0x0000000000422e79 in _start ()\n\n=================================================================\nGot a SIGABRT while executing native code. This usually indicates\na fatal error in the mono runtime or one of the native libraries \nused by your application.\n=================================================================\n\n\n    at /home/javier/projects/electron-installer-windows/example/node_modules/electron-installer-windows/src/installer.js:273:21\n    at ChildProcess.<anonymous> (/home/javier/projects/electron-installer-windows/example/node_modules/electron-installer-windows/src/installer.js:62:5)\n    at emitTwo (events.js:130:20)\n    at ChildProcess.emit (events.js:213:7)\n    at maybeClose (internal/child_process.js:897:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poopie@0.0.1 set32: `electron-installer-windows --src dist/poopie-win32-ia32/ --dest dist/installers/ia32/ --config config.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the poopie@0.0.1 set32 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/javier/.npm/_logs/2017-09-04T18_39_32_411Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poopie@0.0.1 build: `npm run clean && npm run exe32 && npm run set32 && npm run exe64 && npm run set64`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the poopie@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/javier/.npm/_logs/2017-09-04T18_39_32_469Z-debug.log

```
**What did you expect to happen?**
.exe file

**Comment by fcastilloec** [comment]
I'm closing this issue and moving any comments to the more recent #226 which is using the latest version
