### ISSUE TITLE
Failed to generate re NuGet

### ISSUE THREAD

**Issue by Stylesoftware** [unindented/electron-installer-windows#226]
**What version of `electron-installer-windows` are you using?**
1.0.2
**What version of `node` and `npm` are you using?**
v8.9.1 and v5.8.0
**What operating system are you using?**
Windows 7 x64
**Can you compile the [example app](https://github.com/unindented/electron-installer-windows/tree/master/example) successfully?**
No
**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/unindented/electron-installer-windows.git
$ cd electron-installer-windows/example
$ DEBUG='electron-installer-windows' npm run build

C:\electron\SS2\electron-installer-windows\example>npm run build

> poopie@0.0.1 build C:\electron\SS2\electron-installer-windows\example
> npm run clean && npm run exe32 && npm run set32 && npm run exe64 && npm run se
t64


> poopie@0.0.1 clean C:\electron\SS2\electron-installer-windows\example
> rimraf dist


> poopie@0.0.1 exe32 C:\electron\SS2\electron-installer-windows\example
> electron-packager . poopie --platform win32 --arch ia32 --out dist/ --icon res
ources/Icon.ico

Packaging app for platform win32 ia32 using electron v1.8.4
Wrote new app to dist\poopie-win32-ia32

> poopie@0.0.1 set32 C:\electron\SS2\electron-installer-windows\example
> electron-installer-windows --src dist/poopie-win32-ia32/ --dest dist/installer
s/ia32/ --config config.json

Creating package (this may take a while)
Error: Error creating package with NuGet: Error executing command (Exited with s
tatus 3762504530):
C:\electron\SS2\electron-installer-windows\example\node_modules\electron-install
er-windows\vendor\nuget\NuGet.exe pack C:\Users\Chris\AppData\Local\Temp\electro
n-884Z8DbMRQC4Siu\poopie_0.0.1\nuget\poopie.nuspec -BasePath C:\Users\Chris\AppD
ata\Local\Temp\electron-884Z8DbMRQC4Siu\poopie_0.0.1\poopie -OutputDirectory C:\
Users\Chris\AppData\Local\Temp\electron-884Z8DbMRQC4Siu\poopie_0.0.1\nuget -NoDe
faultExcludes

Unhandled Exception: System.MissingMethodException: Method not found: '!!0[] Sys
tem.Array.Empty()'.
   at NuGet.Common.CommandLineResponseFile.ParseArgsResponseFiles(String[] args,
 Int32 parseArgsResponseFileRecursionDepth)
   at NuGet.CommandLine.Program.Main(String[] args)

    at err (C:\electron\SS2\electron-installer-windows\example\node_modules\elec
tron-installer-windows\src\installer.js:31:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) 'Error: Error
 creating package with NuGet: Error executing command (Exited with status 376250
4530):\nC:\\electron\\SS2\\electron-installer-windows\\example\\node_modules\\el
ectron-installer-windows\\vendor\\nuget\\NuGet.exe pack C:\\Users\\Chris\\AppDat
a\\Local\\Temp\\electron-884Z8DbMRQC4Siu\\poopie_0.0.1\\nuget\\poopie.nuspec -Ba
sePath C:\\Users\\Chris\\AppData\\Local\\Temp\\electron-884Z8DbMRQC4Siu\\poopie_
0.0.1\\poopie -OutputDirectory C:\\Users\\Chris\\AppData\\Local\\Temp\\electron-
884Z8DbMRQC4Siu\\poopie_0.0.1\\nuget -NoDefaultExcludes\n\nUnhandled Exception:
System.MissingMethodException: Method not found: \'!!0[] System.Array.Empty()\'.
\r\n   at NuGet.Common.CommandLineResponseFile.ParseArgsResponseFiles(String[] a
rgs, Int32 parseArgsResponseFileRecursionDepth)\r\n   at NuGet.CommandLine.Progr
am.Main(String[] args)\n\n    at err (C:\\electron\\SS2\\electron-installer-wind
ows\\example\\node_modules\\electron-installer-windows\\src\\installer.js:31:11)
\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.j
s:188:7)'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poopie@0.0.1 set32: `electron-installer-windows --src dist/poopie-win32
-ia32/ --dest dist/installers/ia32/ --config config.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the poopie@0.0.1 set32 script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chris\AppData\Roaming\npm-cache\_logs\2018-04-09T03_50_53_
467Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poopie@0.0.1 build: `npm run clean && npm run exe32 && npm run set32 &&
 npm run exe64 && npm run set64`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the poopie@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chris\AppData\Roaming\npm-cache\_logs\2018-04-09T03_50_53_
576Z-debug.log
---
**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
used github example no changes

**What did you expect to happen?**
build installer

**What actually happened?**
error above

**Comment by fcastilloec** [comment]
I couldn't reproduce this error. I think the problem you're having is specifically related to this:

> Unhandled Exception: System.MissingMethodException: Method not found: '!!0[] Sys
tem.Array.Empty()'.

A simple google search tells me that you probably don't have the latest .Net version installed, or at least anything greater than v4. Try install the latest version of .Net and see if this goes away.

**Comment by Stylesoftware** [comment]
Hi,
After several simple google searches, I found it is not Dot Net that needed to be installed, so far it seems I may need Visual Studio and possibly SP1 for Win7, but thanks for putting me roughly on the right track.

**Comment by Madhumitha10** [comment]
'Error: Error creating package with NuGet: Error executing command (Exited with status 1):\nE:\\sample\\node_modules\\electron-installer-windows\\vendor\\nuget\\nuget.exe pack C:\\Users\\DEV100~1\\AppData\\Local\\Temp\\electron-21960AqMNUeekF6v7\\sample_1.0.0_undefined\\nuget\\sample.nuspec -BasePath C:\\Users\\DEV100~1\\AppData\\Local\\Temp\\electron-21960AqMNUeekF6v7\\sample_1.0.0_undefined\\sample -OutputDirectory C:\\Users\\DEV100~1\\AppData\\Local\\Temp\\electron-21960AqMNUeekF6v7\\sample_1.0.0_undefined\\nuget -NoDefaultExcludes\nThe element \'metadata\' in namespace \'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd\' has incomplete content. List of possible elements expected: \'description\' in namespace \'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd\'. This validation error occurred in a \'metadata\' element.\r\n\n    at spawn.then.catch.err (E:\\sample\\node_modules\\electron-installer-common\\src\\spawn.js:21:13)\n    at process._tickCallback (internal/process/next_tick.js:68:7)'

**Comment by Madhumitha10** [comment]
How to handle this situation
