### ISSUE TITLE
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: WriteEntryTo or OpenEntryStream can only be called once.

### ISSUE THREAD

**Issue by liudonghua123** [unindented/electron-installer-windows#231]
I want to package a electron app which build with [nativefier](https://github.com/jiahaog/nativefier), but I got the following errors.
```
D:\code>electron-installer-windows --src weixin/video_app-win32-x64 --dest weixin/app-dist
Creating package (this may take a while)
Error: Error releasifying package: Error executing command (Exited with status 4294967295):
C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\squirrel\Squirrel.com --releasify C:/Users/LIUD~1.H/AppData/Local/Temp/electron-32536A5WmCI6xjasm/video-app-nativefier-478075_1.0.0/nuget/video-app-nativefier-478075.1.0.0.nupkg --releaseDir C:\Users\LIUD~1.H\AppData\Local\Temp\electron-32536A5WmCI6xjasm\video-app-nativefier-478075_1.0.0\squirrel --setupIcon C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\electron-installer-windows\resources\icon.ico --loadingGif C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\electron-installer-windows\resources\animation.gif
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: WriteEntryTo or OpenEntryStream can only be called once.
   at SharpCompress.Readers.AbstractReader`2.WriteEntryTo(Stream writableStream)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToFile(IReader reader, String destinationFileName, ExtractionOptions options)
   at Squirrel.ReleasePackage.<>c__DisplayClass14_2.<extractZipWithEscaping>b__2()
   at Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()
   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   at Squirrel.Utility.Retry(Action block, Int32 retries)
   at Squirrel.ReleasePackage.<>c__DisplayClass14_0.<extractZipWithEscaping>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.ArgumentException: WriteEntryTo or OpenEntryStream can only be called once.
   at SharpCompress.Readers.AbstractReader`2.WriteEntryTo(Stream writableStream)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToFile(IReader reader, String destinationFileName, ExtractionOptions options)
   at Squirrel.ReleasePackage.<>c__DisplayClass14_2.<extractZipWithEscaping>b__2()
   at Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()
   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   at Squirrel.Utility.Retry(Action block, Int32 retries)
   at Squirrel.ReleasePackage.<>c__DisplayClass14_0.<extractZipWithEscaping>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---


    at err (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\electron-installer-windows\src\installer.js:31:11)
    at process._tickCallback (internal/process/next_tick.js:178:7) 'Error: Error releasifying package: Error executing command (Exited with status 4294967295):\nC:\\Users\\Liu.D.H\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\vendor\\squirrel\\Squirrel.com --releasify C:/Users/LIUD~1.H/AppData/Local/Temp/electron-32536A5WmCI6xjasm/video-app-nativefier-478075_1.0.0/nuget/video-app-nativefier-478075.1.0.0.nupkg --releaseDir C:\\Users\\LIUD~1.H\\AppData\\Local\\Temp\\electron-32536A5WmCI6xjasm\\video-app-nativefier-478075_1.0.0\\squirrel --setupIcon C:\\Users\\Liu.D.H\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\resources\\icon.ico --loadingGif C:\\Users\\Liu.D.H\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\resources\\animation.gif\nSystem.AggregateException: One or more errors occurred. ---> System.ArgumentException: WriteEntryTo or OpenEntryStream can only be called once.\r\n   at SharpCompress.Readers.AbstractReader`2.WriteEntryTo(Stream writableStream)\r\n   at SharpCompress.Readers.IReaderExtensions.WriteEntryToFile(IReader reader, String destinationFileName, ExtractionOptions options)\r\n   at Squirrel.ReleasePackage.<>c__DisplayClass14_2.<extractZipWithEscaping>b__2()\r\n   at Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()\r\n   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)\r\n   at Squirrel.Utility.Retry(Action block, Int32 retries)\r\n   at Squirrel.ReleasePackage.<>c__DisplayClass14_0.<extractZipWithEscaping>b__0()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)\r\n   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)\r\n   at Squirrel.Update.Program.executeCommandLine(String[] args)\r\n   at Squirrel.Update.Program.main(String[] args)\r\n   at Squirrel.Update.Program.Main(String[] args)\r\n---> (Inner Exception #0) System.ArgumentException: WriteEntryTo or OpenEntryStream can only be called once.\r\n   at SharpCompress.Readers.AbstractReader`2.WriteEntryTo(Stream writableStream)\r\n   at SharpCompress.Readers.IReaderExtensions.WriteEntryToFile(IReader reader, String destinationFileName, ExtractionOptions options)\r\n   at Squirrel.ReleasePackage.<>c__DisplayClass14_2.<extractZipWithEscaping>b__2()\r\n   at Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()\r\n   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)\r\n   at Squirrel.Utility.Retry(Action block, Int32 retries)\r\n   at Squirrel.ReleasePackage.<>c__DisplayClass14_0.<extractZipWithEscaping>b__0()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()<---\r\n\r\n\n    at err (C:\\Users\\Liu.D.H\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\src\\installer.js:31:11)\n    at process._tickCallback (internal/process/next_tick.js:178:7)'

D:\code>
```

**Comment by fcastilloec** [comment]
Sorry, but this tools works exclusively with `electron-packager` as it's stated in the README. `nativefier` might create a different file structure that this app can't handle.
