### ISSUE TITLE
NPM script error: expecting "authors" metadata in namespace?

### ISSUE THREAD

**Issue by Mercieral** [unindented/electron-installer-windows#39]
**What version of `electron-installer-windows` are you using?**
0.2.0

**What version of `node` and `npm` are you using?**
npm 2.14.20
node 4.4.0

**What operating system are you using?**
Mac OS X El Capitan 10.11.5

**Can you compile the [example app](https://github.com/unindented/electron-installer-windows/tree/master/example) successfully?**
Yes 

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
Running as an NPM script "packageWIN": "electron-installer-windows --src=./packaged/gg-win32-x64/ --dest=./packaged"

**What happened?**
Creating package (this may take a while)
[Error: Error creating package: Error executing file (1): 
mono /Users/tester/company/project/node_modules/electron-installer-windows/vendor/nuget/NuGet.exe pack /var/folders/fb/_hrnxyqs4cvb4f8plq1tv1xr0000gp/T/electron-11668-7220-9l723d/gg_0.1.0/nuget/gg.nuspec -BasePath /var/folders/fb/_hrnxyqs4cvb4f8plq1tv1xr0000gp/T/electron-11668-7220-9l723d/gg_0.1.0/gg -OutputDirectory /var/folders/fb/_hrnxyqs4cvb4f8plq1tv1xr0000gp/T/electron-11668-7220-9l723d/gg_0.1.0/nuget -NoDefaultExcludes
The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd' has incomplete content. List of possible elements expected: 'authors' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd'.
] 'Error: Error creating package: Error executing file (1): \nmono /Users/tester/company/project/node_modules/electron-installer-windows/vendor/nuget/NuGet.exe pack /var/folders/fb/_hrnxyqs4cvb4f8plq1tv1xr0000gp/T/electron-11668-7220-9l723d/gg_0.1.0/nuget/gg.nuspec -BasePath /var/folders/fb/_hrnxyqs4cvb4f8plq1tv1xr0000gp/T/electron-11668-7220-9l723d/gg_0.1.0/gg -OutputDirectory /var/folders/fb/_hrnxyqs4cvb4f8plq1tv1xr0000gp/T/electron-11668-7220-9l723d/gg_0.1.0/nuget -NoDefaultExcludes\nThe element \'metadata\' in namespace \'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd\' has incomplete content. List of possible elements expected: \'authors\' in namespace \'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd\'.\n\n    at /Users/tester/company/project/node_modules/electron-installer-windows/src/installer.js:273:21\n    at ChildProcess.<anonymous> (/Users/tester/company/project/node_modules/electron-installer-windows/src/installer.js:62:5)\n    at emitTwo (events.js:92:20)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:827:16)\n    at Socket.<anonymous> (internal/child_process.js:319:11)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at Pipe._onclose (net.js:475:12)'

**Comment by unindented** [comment]
The key is in this error message: "The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd' has incomplete content. List of possible elements expected: 'authors' in namespace "

Try including an `author` in your `package.json` file, or passing the [`authors` option](https://github.com/unindented/electron-installer-windows#optionsauthors).

**Comment by Mercieral** [comment]
Thank you, I was trying to follow the readme to the point but I didn't realize my package.json didn't have an authors field. 

Thankfully it is building now but the install is failing unfortunately. Is the installer compatible with windows 10?

Heres the SquirrelSetup dump 
```
2016-07-08 13:11:34> Program: Starting Squirrel Updater: --install .
2016-07-08 13:11:34> Program: Starting install, writing to C:\Users\mercieal\AppData\Local\SquirrelTemp
2016-07-08 13:11:34> Program: About to install to: C:\Users\mercieal\AppData\Local\gg
2016-07-08 13:11:34> Program: Install path C:\Users\mercieal\AppData\Local\gg already exists, burning it to the ground
2016-07-08 13:11:34> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\mercieal\AppData\Local\gg\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2016-07-08 13:11:34> CheckForUpdateImpl: Reading RELEASES file from C:\Users\mercieal\AppData\Local\SquirrelTemp
2016-07-08 13:11:35> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-07-08 13:11:35> ApplyReleasesImpl: Writing files to app directory: C:\Users\mercieal\AppData\Local\gg\app-0.1.0
2016-07-08 13:11:37> ApplyReleasesImpl: Moving file C:\Users\mercieal\AppData\Local\gg\app-0.1.0\lib\net45\content_resources_200_percent.pak to C:\Users\mercieal\AppData\Local\gg\app-0.1.0\content_resources_200_percent.pak
2016-07-08 13:11:37> ApplyReleasesImpl: Moving file C:\Users\mercieal\AppData\Local\gg\app-0.1.0\lib\net45\d3dcompiler_47.dll to C:\Users\mercieal\AppData\Local\gg\app-0.1.0\d3dcompiler_47.dll
2016-07-08 13:11:37> ApplyReleasesImpl: Moving file C:\Users\mercieal\AppData\Local\gg\app-0.1.0\lib\net45\content_shell.pak to C:\Users\mercieal\AppData\Local\gg\app-0.1.0\content_shell.pak
2016-07-08 13:11:37> ApplyReleasesImpl: Moving file C:\Users\mercieal\AppData\Local\gg\app-0.1.0\lib\net45\ffmpeg.dll to C:\Users\mercieal\AppData\Local\gg\app-0.1.0\ffmpeg.dll
2016-07-08 13:11:37> ApplyReleasesImpl: Moving file C:\Users\mercieal\AppData\Local\gg\app-0.1.0\lib\net45\gg.exe to C:\Users\mercieal\AppData\Local\gg\app-0.1.0\gg.exe
2016-07-08 13:11:37> ApplyReleasesImpl: Moving file C:\Users\mercieal\AppData\Local\gg\app-0.1.0\lib\net45\icudtl.dat to C:\Users\mercieal\AppData\Local\gg\app-0.1.0\icudtl.dat
2016-07-08 13:11:37> ApplyReleasesImpl: Moving file C:\Users\mercieal\AppData\Local\gg\app-0.1.0\lib\net45\libEGL.dll to C:\Users\mercieal\AppData\Local\gg\app-0.1.0\libEGL.dll
2016-07-08 13:11:37> ApplyReleasesImpl: Moving file C:\Users\mercieal\AppData\Local\gg\app-0.1.0\lib\net45\libGLESv2.dll to C:\Users\mercieal\AppData\Local\gg\app-0.1.0\libGLESv2.dll
2016-07-08 13:11:37> ApplyReleasesImpl: Moving file C:\Users\mercieal\AppData\Local\gg\app-0.1.0\lib\net45\LICENSE to C:\Users\mercieal\AppData\Local\gg\app-0.1.0\LICENSE
2016-07-08 13:11:37> ApplyReleasesImpl: Moving file C:\Users\mercieal\AppData\Local\gg\app-0.1.0\lib\net45\natives_blob.bin to C:\Users\mercieal\AppData\Local\gg\app-0.1.0\natives_blob.bin
2016-07-08 13:11:37> ApplyReleasesImpl: Moving file C:\Users\mercieal\AppData\Local\gg\app-0.1.0\lib\net45\node.dll to C:\Users\mercieal\AppData\Local\gg\app-0.1.0\node.dll
2016-07-08 13:11:37> ApplyReleasesImpl: Moving file C:\Users\mercieal\AppData\Local\gg\app-0.1.0\lib\net45\snapshot_blob.bin to C:\Users\mercieal\AppData\Local\gg\app-0.1.0\snapshot_blob.bin
2016-07-08 13:11:37> ApplyReleasesImpl: Moving file C:\Users\mercieal\AppData\Local\gg\app-0.1.0\lib\net45\squirrel.exe to C:\Users\mercieal\AppData\Local\gg\app-0.1.0\squirrel.exe
2016-07-08 13:11:37> ApplyReleasesImpl: Moving file C:\Users\mercieal\AppData\Local\gg\app-0.1.0\lib\net45\xinput1_3.dll to C:\Users\mercieal\AppData\Local\gg\app-0.1.0\xinput1_3.dll
2016-07-08 13:11:37> ApplyReleasesImpl: Moving file C:\Users\mercieal\AppData\Local\gg\app-0.1.0\lib\net45\ui_resources_200_percent.pak to C:\Users\mercieal\AppData\Local\gg\app-0.1.0\ui_resources_200_percent.pak
2016-07-08 13:11:39> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\mercieal\AppData\Local\gg\app-0.1.0\gg.exe]
2016-07-08 13:11:39> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-07-08 13:11:39> ApplyReleasesImpl: Examining Pin: Eclipse.lnk
2016-07-08 13:11:39> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2016-07-08 13:11:39> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2016-07-08 13:11:39> ApplyReleasesImpl: Examining Pin: Sublime Text 3.lnk
2016-07-08 13:11:39> ApplyReleasesImpl: Fixing up tray icons
2016-07-08 13:11:39> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2016-07-08 13:11:39> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2016-07-08 13:11:39> ApplyReleasesImpl: cleanDeadVersions: for version 0.1.0
2016-07-08 13:11:39> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.1.0
2016-07-08 13:11:39> IEnableLogger: Failed to create uninstaller registry entry: System.Xml.XmlException: 'Default' tag requires a nonempty 'Extension' attribute. Line 10, position 4.
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ValidateXmlAttribute(String attributeName, String attributeValue, String tagName, XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ProcessDefaultTagAttributes(XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ParseContentTypesFile(ZipFileInfoCollection zipFiles)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at NuGet.ZipPackage..ctor(String filePath)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2016-07-08 13:11:39> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Xml.XmlException: 'Default' tag requires a nonempty 'Extension' attribute. Line 10, position 4.
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ValidateXmlAttribute(String attributeName, String attributeValue, String tagName, XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ProcessDefaultTagAttributes(XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ParseContentTypesFile(ZipFileInfoCollection zipFiles)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at NuGet.ZipPackage..ctor(String filePath)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Xml.XmlException: 'Default' tag requires a nonempty 'Extension' attribute. Line 10, position 4.
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ValidateXmlAttribute(String attributeName, String attributeValue, String tagName, XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ProcessDefaultTagAttributes(XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ParseContentTypesFile(ZipFileInfoCollection zipFiles)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at NuGet.ZipPackage..ctor(String filePath)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---
```

**Comment by unindented** [comment]
Try creating the directory `C:\Users\mercieal\AppData\Local\`, and try again.
